name: Pikabo Workflow
on: workflow_dispatch
jobs:
  Build_And_Publish:
   runs-on: ubuntu-latest
   steps:
     - name: Code checkout
       uses: actions/checkout@v4

   #  - name: Set up QEMU
   #    uses: docker/setup-qemu-action@v3

   #  - name: Set up Docker Buildx
   #    uses: docker/setup-buildx-action@v3

   #  - name: Login to Docker Hub
   #    uses: docker/login-action@v3
   #    with:
   #       username: ${{ secrets.DOCKERHUB_USERNAME }}
   #       password: ${{ secrets.DOCKERHUB_TOKEN }}

     #- name: upload image to ECR
     #  uses: appleboy/docker-ecr-action@master
     #  with:
     #    access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
     #    secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     #    registry: ${{ secrets.REGISTRY }}
     #    repo: api-sample
     #    region: us-east-2
     #    auto_tag: true
     #    daemon_off: false
     #    dockerfile: ./Dockerfile
     #a    context: ./
     - name: BUILD AND PUSH TO ECR
       uses: docker://ghcr.io/kciter/aws-ecr-action:latest
       with:
         access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         account_id: 716657688884
         repo: actapp
         region: us-east-2
         #tags: latest,${{ github.sha }}         
         tags: latest
         dockerfile: ./Dockerfile
         #image_scanning_configuration: true
#         set_repo_policy: true
#         repo_policy_file: repo-policy.json
     
     #- name: Build and push
     #  uses: docker/build-push-action@v5
     #  with:
     #     context: ./
     #     push: true
     #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/actapp:${{ github.run_number }},${{ secrets.DOCKERHUB_USERNAME }}/actapp:latest 
